src/BoInsurance/Controllers/VerificationController.cs
using Insurance.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Insurance.Controllers
{
    [ApiController]
    [Route("/api/[controller]")]
    public class VerificationController : Controller
    {
        private readonly IDriversLicenseVerificationService _diversLicenseVerificationService;

        public VerificationController(IDriversLicenseVerificationService diversLicenseVerificationService)
        {
            _diversLicenseVerificationService = diversLicenseVerificationService;
        }

        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> CheckStatus(string verificationId)
        {
            var verificationState = await _diversLicenseVerificationService.GetVerificationState(verificationId);
            return Ok(new { state = verificationState });
        }
    }
}

src/BoInsurance/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Insurance.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/BoInsurance/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Insurance.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

src/BoInsurance/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Insurance.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/BoInsurance/Pages/SignUp.cshtml.cs
using Insurance.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace BoInsurance.Pages
{
    [ValidateAntiForgeryToken]
    public class SignUpModel : PageModel
    {
        [BindProperty]
        public InputModel Input { get; set; } = new InputModel();

        public string VerificationUrl { get; set; }

        private readonly IDriversLicenseVerificationService _diversLicenseVerificationService;

        public SignUpModel(IDriversLicenseVerificationService diversLicenseVerificationService)
        {
            _diversLicenseVerificationService = diversLicenseVerificationService;
        }

        public class InputModel
        {
            public string VerificationId { get; set; }

            public string Name { get; set; }

            [Display(Name = "First name")]
            public string FirstName { get; set; }

            public string Address { get; set; }

            public string Zip { get; set; }

            public string City { get; set; }
        }

        public async Task OnGetAsync()
        {
            var verificationRequest = await _diversLicenseVerificationService.CreateVerificationRequest();
            VerificationUrl = verificationRequest.verificationUrl;
            Input.VerificationId = verificationRequest.verificationId;
        }

        public IActionResult OnPost()
        {
            // Implement your custom logic here..
            // Make sure the VerificationId was accepted...
            // For example create an account for the user and allow him to login to the insurance applicaiton with his driver license.

            return RedirectToPage("/success", new { verificationId = Input.VerificationId });
        }
    }
}

src/BoInsurance/Pages/Success.cshtml.cs
using Insurance.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace BoInsurance.Pages
{
    public class SuccessModel : PageModel
    {
        public string JsonResponse { get; set; }

        private readonly IDriversLicenseVerificationService _diversLicenseVerificationService;

        public SuccessModel(IDriversLicenseVerificationService diversLicenseVerificationService)
        {
            _diversLicenseVerificationService = diversLicenseVerificationService;
        }

        public async Task OnGetAsync(string verificationId)
        {
            JsonResponse = await _diversLicenseVerificationService.GetVerification(verificationId);
        }
    }
}

src/BoInsurance/Pages/Index.cshtml
@page
@model IndexModel
@{ ViewData["Title"] = "Home page"; }


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <img src="~/ndl_insurance_01.png" />
        </div>
        <div class="col-sm-8">
            <div class="text-center">
                <br />
                <h4>Premium Discount Car Insurance</h4>
            </div>
        </div>
    </div>
</div>

<div class="card-deck mb-3 text-center">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Premium Discount Car Insurance Package</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
                <li>30% off</li>
                <li>No fee for monthly payment</li>
                <li>And more</li>
            </ul>
            <a asp-page="SignUp" class="btn btn-lg btn-block btn-outline-primary">Create new insurance</a>
        </div>
    </div>
</div>

src/BoInsurance/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Insurance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fontawesome-free-5.15.2-web/css/all.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Bo Insurance</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Bo Insurance - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/BoInsurance/Pages/SignUp.cshtml
@page "/signup"

@model BoInsurance.Pages.SignUpModel

@{
    ViewData["Title"] = "Sign Up";
}

<div class="card">
    <h5 class="card-header">Sign Up Form</h5>
    <div class="card-body">
        <p>Please provide us with your address so that we can create a contract for you.</p>
        <form id="signUpForm" method="POST">
            <input type="hidden" asp-for="@Model.Input.VerificationId" />
            <div class="form-group">
                <label asp-for="@Model.Input.Name"></label>
                <input class="form-control" asp-for="@Model.Input.Name" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Input.FirstName"></label>
                <input class="form-control" asp-for="@Model.Input.FirstName" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Input.Address"></label>
                <input class="form-control" asp-for="@Model.Input.Address" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Input.Zip"></label>
                <input class="form-control" asp-for="@Model.Input.Zip" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Input.City"></label>
                <input class="form-control" asp-for="@Model.Input.City" />
            </div>
            <div class="form-group d-flex flex-column align-items-center">
                <p id="qrCodeLabel">Verify your driver license: Scan QR Code using your Digital wallet</p>
                <div id="qrCode" class="qr"></div>
                <div id="success" class="text-center" style="display: none;">
                    <img width="300" src="~/check-mark-icon-vector.jpg" />
                    <p>Thank you for your verification. You may now submit the form.</p>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {

    <script>
        $(function () {
            new QRCode(document.getElementById('qrCode'),
            {
                text: '@Model.VerificationUrl',
                width: 300,
                height: 300
            });

            // Start polling so that we know when we can move on
            var intervalId = setInterval(function () {
                console.log('Checking verification status');
                $.ajax({
                    url: '@(Url.ActionLink("CheckStatus", "Verification", new { verificationId = Model.Input.VerificationId}))',
                    success: function (data) {
                        console.log(JSON.stringify(data));
                        if (data.state === "accepted") {
                            clearInterval(intervalId);

                            console.log('Thank you for your verification!');

                            $('#qrCode').hide();
                            $('#qrCodeLabel').hide();
                            $('#success').show();
                        }
                    }
                });
            }, 2000);
        });
    </script>
    <script src="~/js/qrcode.min.js"></script>
} 

src/BoInsurance/Pages/Success.cshtml
@page "/success/{verificationId}"
@model BoInsurance.Pages.SuccessModel


@{ ViewData["Title"] = "Success"; }


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                <br />
                <h4>You have successfully created a new car insurance with us.</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    Verification Response
                </div>
                <div class="card-body">
                    <p class="m-0">
                        <code>
                            @Model.JsonResponse
                        </code>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>